universe = vanilla
initialdir = /home/storm.colloms/O4a_population/test_gwpopulationpipe
executable = /home/storm.colloms/.conda/envs/O4apop/bin/gwpopulation_pipe_to_common_format
output = /home/storm.colloms/O4a_population/test_gwpopulationpipe/O4a_variablem2min_nestlenlive50/logs/population-format-$(label).out
error = /home/storm.colloms/O4a_population/test_gwpopulationpipe/O4a_variablem2min_nestlenlive50/logs/population-format-$(label).err
log = /home/storm.colloms/O4a_population/test_gwpopulationpipe/O4a_variablem2min_nestlenlive50/logs/population-format-$(label).log
request_cpus = 1
request_gpus = 0
request_memory = 1GB
request_disk = 200MB
accounting_group = ligo.dev.o4.cbc.bayesianpopulations.parametric
accounting_group_user = storm.colloms
notification = error
arguments = --result-file O4a_variablem2min_nestlenlive50/result/$(label)_result.hdf5 --n-samples 5000 --max-redshift 1.9 --minimum-mass 2.0 --maximum-mass 100.0 --injection-file O4a_variablem2min_nestlenlive50/data/injections.pkl --filename O4a_variablem2min_nestlenlive50/result/$(label)_full_posterior.hdf5 --samples-file O4a_variablem2min_nestlenlive50/result/$(label)_samples.pkl --vt-ifar-threshold 1.0 --vt-snr-threshold 10.0 --backend numpy 
checkpoint_exit_code = 130
should_transfer_files = YES
transfer_input_files = O4a_variablem2min_nestlenlive50/result/$(label)_result.hdf5,O4a_variablem2min_nestlenlive50/data/injections.pkl,O4a_variablem2min_nestlenlive50/result/$(label)_samples.pkl
transfer_output_files = O4a_variablem2min_nestlenlive50/result/$(label)_full_posterior.hdf5
when_to_transfer_output = ON_EXIT_OR_EVICT
preserve_relative_paths = True
stream_error = True
stream_output = True

queue