universe = vanilla
initialdir = /home/storm.colloms/O4a_population/variable_qmin_inference
executable = /home/storm.colloms/.conda/envs/O4apop/bin/gwpopulation_pipe_collection
output = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_parabolam2min_prod_allgammazeta/logs/population-collection-$(label).out
error = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_parabolam2min_prod_allgammazeta/logs/population-collection-$(label).err
log = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_parabolam2min_prod_allgammazeta/logs/population-collection-$(label).log
request_cpus = 1
request_gpus = 0
request_memory = 8GB
request_disk = 200MB
accounting_group = ligo.dev.o4.cbc.bayesianpopulations.parametric
accounting_group_user = storm.colloms
notification = error
arguments = O1O2O3_parabolam2min_prod_allgammazeta/bbh_config_complete.ini --run-dir O1O2O3_parabolam2min_prod_allgammazeta
checkpoint_exit_code = 130
should_transfer_files = NO

queue