universe = vanilla
initialdir = /home/storm.colloms/O4a_population/variable_qmin_inference
executable = /home/storm.colloms/.conda/envs/O4apop-jax/bin/gwpopulation_pipe_plot
output = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_parabolam2min_prod_allgammazeta_jax/logs/population-plot-$(label).out
error = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_parabolam2min_prod_allgammazeta_jax/logs/population-plot-$(label).err
log = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_parabolam2min_prod_allgammazeta_jax/logs/population-plot-$(label).log
request_cpus = 1
request_gpus = 1
request_memory = 1GB
request_disk = 1GB
accounting_group = ligo.dev.o4.cbc.bayesianpopulations.parametric
accounting_group_user = storm.colloms
notification = error
arguments = O1O2O3_parabolam2min_prod_allgammazeta_jax/bbh_config_complete.ini --run-dir O1O2O3_parabolam2min_prod_allgammazeta_jax --result-file O1O2O3_parabolam2min_prod_allgammazeta_jax/result/$(label)_result.hdf5 --samples O1O2O3_parabolam2min_prod_allgammazeta_jax/result/$(label)_samples.pkl 
checkpoint_exit_code = 130
require_gpus = DeviceName=="GeForce GTX 1050 Ti"
should_transfer_files = YES
transfer_input_files = O1O2O3_parabolam2min_prod_allgammazeta_jax/bbh_config_complete.ini,O1O2O3_parabolam2min_prod_allgammazeta_jax/result/$(label)_result.hdf5,O1O2O3_parabolam2min_prod_allgammazeta_jax/result/$(label)_samples.pkl,O1O2O3_parabolam2min_prod_allgammazeta_jax/data/injections.pkl
transfer_output_files = O1O2O3_parabolam2min_prod_allgammazeta_jax/result
when_to_transfer_output = ON_EXIT_OR_EVICT
preserve_relative_paths = True
stream_error = True
stream_output = True

queue