universe = vanilla
initialdir = /home/storm.colloms/O4a_population/variable_qmin_inference
executable = /home/storm.colloms/.conda/envs/O4apop-jax/bin/gwpopulation_pipe_analysis
output = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_powerlawm2min_prod_fewerevents_no190814/logs/population-analysis-$(label).out
error = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_powerlawm2min_prod_fewerevents_no190814/logs/population-analysis-$(label).err
log = /home/storm.colloms/O4a_population/variable_qmin_inference/O1O2O3_powerlawm2min_prod_fewerevents_no190814/logs/population-analysis-$(label).log
request_cpus = 1
request_gpus = 1
request_memory = 16GB
request_disk = 1GB
accounting_group = ligo.dev.o4.cbc.bayesianpopulations.parametric
accounting_group_user = storm.colloms
notification = error
arguments = O1O2O3_powerlawm2min_prod_fewerevents_no190814/bbh_config_complete.ini --run-dir O1O2O3_powerlawm2min_prod_fewerevents_no190814 --label $(label) $(models) $(vt_models) --vt-file O1O2O3_powerlawm2min_prod_fewerevents_no190814/data/injections.pkl
checkpoint_exit_code = 130
require_gpus = DeviceName=="GeForce GTX 1050 Ti"
should_transfer_files = YES
transfer_input_files = O1O2O3_powerlawm2min_prod_fewerevents_no190814/data/posteriors.pkl,O1O2O3_powerlawm2min_prod_fewerevents_no190814/data/posteriors_posterior_files.txt,O1O2O3_powerlawm2min_prod_fewerevents_no190814/data/injections.pkl,/home/storm.colloms/O4a_population/variable_qmin_inference/O4a-PLm2min.prior,O1O2O3_powerlawm2min_prod_fewerevents_no190814/bbh_config_complete.ini,O1O2O3_powerlawm2min_prod_fewerevents_no190814/result/$(label)_dynesty.pickle,O1O2O3_powerlawm2min_prod_fewerevents_no190814/result/$(label)_result.hdf5,O1O2O3_powerlawm2min_prod_fewerevents_no190814/result/$(label)_resume.pickle
transfer_output_files = O1O2O3_powerlawm2min_prod_fewerevents_no190814/result
when_to_transfer_output = ON_EXIT_OR_EVICT
preserve_relative_paths = True
stream_error = True
stream_output = True

queue