universe = vanilla
initialdir = /home/storm.colloms/O4a_population/test_gwpopulationpipe
executable = /home/storm.colloms/.conda/envs/O4apop/bin/summarypages
output = /home/storm.colloms/O4a_population/test_gwpopulationpipe/O4a_variablem2min_dynesty/logs/population-summary-$(label).out
error = /home/storm.colloms/O4a_population/test_gwpopulationpipe/O4a_variablem2min_dynesty/logs/population-summary-$(label).err
log = /home/storm.colloms/O4a_population/test_gwpopulationpipe/O4a_variablem2min_dynesty/logs/population-summary-$(label).log
request_cpus = 1
request_gpus = 0
request_memory = 1GB
request_disk = 200MB
accounting_group = ligo.dev.o4.cbc.bayesianpopulations.parametric
accounting_group_user = storm.colloms
notification = error
arguments = --config O4a_variablem2min_dynesty/bbh_config_complete.ini --webdir O4a_variablem2min_dynesty/summary --samples O4a_variablem2min_dynesty/result/bbh_mass_two_component_primary_mass_ratio_variable_qmin_redshift_powerlaw_result.hdf5 --labels bbh_mass_two_component_primary_mass_ratio_variable_qmin_redshift_powerlaw
checkpoint_exit_code = 130
environment = CONDA_EXE=/cvmfs/software.igwn.org/conda/bin/conda
should_transfer_files = YES
transfer_input_files = O4a_variablem2min_dynesty/bbh_config_complete.ini,O4a_variablem2min_dynesty/result/bbh_mass_two_component_primary_mass_ratio_variable_qmin_redshift_powerlaw_result.hdf5
transfer_output_files = O4a_variablem2min_dynesty/summary
when_to_transfer_output = ON_EXIT_OR_EVICT
preserve_relative_paths = True
stream_error = True
stream_output = True

queue